### ISSUE TITLE
The weights of pytorch or Caffe convert to keras

### ISSUE THREAD

**Issue by xjcvip007** [GKalliatakis/Keras-VGG16-places365#1]
hello,how can you get your vgg weights of keras ,directly convert it from caffe?if so ,did you have resnet50 or densenet  weights?Thx~

**Comment by GKalliatakis** [comment]
There is no way to convert Caffe models directly to Keras, that's why you need to rebuild the architecture of the model and then load the dumped out weights from Caffe. 

ResNet-50 is [here ](https://github.com/fchollet/keras/blob/master/keras/applications/resnet50.py)

For DenseNet have a look [here ](https://github.com/titu1994/DenseNet)

**Comment by xjcvip007** [comment]
ok,thx for your response~
